require 'nokogiri'
require 'base64'

module Jekyll
  module AutoPlaygroundButtons
    # Hook into Jekyll's post-render phase
    Jekyll::Hooks.register [:pages, :documents], :post_render do |doc|
      # Only process HTML files
      next unless doc.output_ext == '.html'
      
      # Parse the HTML
      html_doc = Nokogiri::HTML(doc.output)
      
      # Find all code blocks with language-isl class (generated by syntax highlighter)
      isl_blocks = html_doc.css('code.language-isl, code.highlighter-rouge')
      
      isl_blocks.each do |code_block|
        # Check if this is actually an ISL code block
        parent_pre = code_block.parent
        next unless parent_pre.name == 'pre'
        
        # Skip if not ISL (check class or content)
        code_classes = code_block['class'].to_s
        next unless code_classes.include?('language-isl') || code_classes.include?('isl')
        
        # Get the ISL code content
        isl_code = code_block.text.strip
        next if isl_code.empty?
        
        # Check if button already exists (don't add duplicates)
        next_sibling = parent_pre.next_element
        if next_sibling && next_sibling['class']&.include?('playground-button-container')
          next
        end
        
        # Look for input JSON in preceding "Input JSON" code block
        input_json = '{}'
        
        # Search backwards for a JSON code block with "Input JSON" heading
        current_element = parent_pre.previous_element
        found_json = false
        
        # Look back up to 10 elements
        10.times do
          break unless current_element
          
          # Check if this is a JSON code block
          if current_element.name == 'pre'
            json_code = current_element.css('code.language-json, code.highlighter-rouge').first
            if json_code
              # Check if there's an "Input JSON" heading before this code block
              heading_check = current_element.previous_element
              
              # Look back a few elements for heading
              3.times do
                break unless heading_check
                
                # Check for heading or bold text containing "Input JSON"
                if heading_check.name =~ /^h\d$/ || heading_check.name == 'p' || heading_check.name == 'strong'
                  heading_text = heading_check.text.strip
                  if heading_text =~ /Input\s+JSON/i
                    # Found it! Extract the JSON
                    input_json = json_code.text.strip
                    found_json = true
                    break
                  end
                end
                
                heading_check = heading_check.previous_element
              end
              
              break if found_json
            end
          end
          
          current_element = current_element.previous_element
        end
        
        # Fallback: Check for HTML comment (for backward compatibility)
        unless found_json
          comment_sibling = parent_pre.next_sibling
          
          5.times do
            break unless comment_sibling
            
            if comment_sibling.comment?
              comment_text = comment_sibling.text.strip
              if comment_text =~ /playground-input:\s*(.+)/i
                input_json = $1.strip
                break
              end
            elsif comment_sibling.element? && comment_sibling.name == 'p'
              inner_comment = comment_sibling.xpath('.//comment()').first
              if inner_comment
                comment_text = inner_comment.text.strip
                if comment_text =~ /playground-input:\s*(.+)/i
                  input_json = $1.strip
                  break
                end
              end
            end
            
            comment_sibling = comment_sibling.next_sibling
          end
        end
        
        # Encode the ISL code using URL-safe base64
        begin
          isl_encoded = Base64.strict_encode64(isl_code)
                              .tr('+/', '-_')
                              .gsub(/=+$/, '')
          
          input_encoded = Base64.strict_encode64(input_json)
                                .tr('+/', '-_')
                                .gsub(/=+$/, '')
        rescue => e
          Jekyll.logger.warn "AutoPlaygroundButtons:", "Failed to encode code block: #{e.message}"
          next
        end
        
        # Create the button HTML
        playground_url = 'https://isl-playground.up.railway.app'
        button_html = %{
<div class="playground-button-container">
  <a href="#{playground_url}?isl_encoded=#{isl_encoded}&input_encoded=#{input_encoded}" 
     target="_blank"
     rel="noopener noreferrer"
     class="btn-playground"
     title="Open this example in the ISL Playground">
    ▶️ Run in Playground
  </a>
</div>
        }.strip
        
        # Insert the button after the pre block
        button_node = Nokogiri::HTML.fragment(button_html)
        parent_pre.add_next_sibling(button_node)
      end
      
      # Update the document output
      doc.output = html_doc.to_html
    end
  end
end

